update: app is stable

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,16 +1,16 @@
 #!/bin/bash
 
 # Name of the Python script
-PYTHON_SCRIPT="script.py"
+PYTHON_SCRIPT="src.server.run"
 
-# Check if the Python script exists
-if [[ ! -f "$PYTHON_SCRIPT" ]]; then
-    echo "Error: $PYTHON_SCRIPT not found!"
-    exit 1
-fi
+# # Check if the Python script exists
+# if [[ ! -f "$PYTHON_SCRIPT" ]]; then
+#     echo "Error: $PYTHON_SCRIPT not found!"
+#     exit 1
+# fi
 
 # Run the Python script
-python3 "$PYTHON_SCRIPT"
+python -m "$PYTHON_SCRIPT"
 
 # Check if the Python script ran successfully
 if [[ $? -eq 0 ]]; then
